"""自动迁移-09241426

Revision ID: 7c66f492687a
Revises: 86a5da24a026
Create Date: 2026-09-24 14:26:44.503950

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c66f492687a'
down_revision: str | None = '86a5da24a026'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_dept',
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='来源类型'),
    sa.Column('source_org_code', sa.String(length=128), nullable=False, comment='来源组织编码'),
    sa.Column('source_code', sa.String(length=128), nullable=False, comment='来源部门编码'),
    sa.Column('source_name', sa.String(length=255), nullable=False, comment='来源部门名称'),
    sa.Column('source_parent_code', sa.String(length=128), nullable=True, comment='来源上级编码'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始数据'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:停用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_source_dept_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_source_dept_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_source_dept_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_dept')),
    sa.UniqueConstraint('source_type', 'source_org_code', 'source_code', name='uq_source_dept'),
    comment='来源部门表'
    )
    with op.batch_alter_table('source_dept', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_dept_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_source_code'), ['source_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_source_org_code'), ['source_org_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_dept_uuid'), ['uuid'], unique=True)

    op.create_table('master_dept',
    sa.Column('org_id', sa.Integer(), nullable=False, comment='所属法人/公司ID'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='组织内部门编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级部门ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='显示排序'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_master_dept_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_master_dept_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['master_org.id'], name=op.f('fk_master_dept_org_id_master_org'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['master_dept.id'], name=op.f('fk_master_dept_parent_id_master_dept'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_master_dept_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_dept')),
    sa.UniqueConstraint('org_id', 'code', name='uq_master_dept_org_code'),
    comment='内部标准部门表'
    )
    with op.batch_alter_table('master_dept', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_dept_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_uuid'), ['uuid'], unique=True)

    op.create_table('master_dept_mapping',
    sa.Column('source_dept_id', sa.Integer(), nullable=False, comment='来源部门ID'),
    sa.Column('master_dept_id', sa.Integer(), nullable=False, comment='内部标准部门ID'),
    sa.Column('match_mode', sa.String(length=16), nullable=False, comment='匹配方式(exact/fuzzy/manual)'),
    sa.Column('confidence', sa.Integer(), nullable=False, comment='匹配置信度(0-100)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:失效)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_master_dept_mapping_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_master_dept_mapping_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['master_dept_id'], ['master_dept.id'], name=op.f('fk_master_dept_mapping_master_dept_id_master_dept'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dept_id'], ['source_dept.id'], name=op.f('fk_master_dept_mapping_source_dept_id_source_dept'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_master_dept_mapping_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_dept_mapping')),
    comment='来源部门映射表'
    )
    with op.batch_alter_table('master_dept_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_master_dept_id'), ['master_dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_source_dept_id'), ['source_dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_dept_mapping_uuid'), ['uuid'], unique=True)

    op.create_table('master_person_org',
    sa.Column('person_id', sa.Integer(), nullable=False, comment='共享人员ID'),
    sa.Column('org_id', sa.Integer(), nullable=False, comment='法人/公司ID'),
    sa.Column('dept_id', sa.Integer(), nullable=True, comment='部门ID'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:失效)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_master_person_org_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_master_person_org_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dept_id'], ['master_dept.id'], name=op.f('fk_master_person_org_dept_id_master_dept'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['master_org.id'], name=op.f('fk_master_person_org_org_id_master_org'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['master_person.id'], name=op.f('fk_master_person_org_person_id_master_person'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_master_person_org_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_person_org')),
    sa.UniqueConstraint('person_id', 'org_id', 'dept_id', name='uq_master_person_org'),
    comment='人员组织部门关系表'
    )
    with op.batch_alter_table('master_person_org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_person_org_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_dept_id'), ['dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_person_org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_person_org_uuid'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_updated_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_person_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_org_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_dept_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_created_time'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_created_id'))

    op.drop_table('master_person_org')
    with op.batch_alter_table('master_dept_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_uuid'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_updated_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_source_dept_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_master_dept_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_created_time'))
        batch_op.drop_index(batch_op.f('ix_master_dept_mapping_created_id'))

    op.drop_table('master_dept_mapping')
    with op.batch_alter_table('master_dept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_dept_uuid'))
        batch_op.drop_index(batch_op.f('ix_master_dept_updated_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_parent_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_org_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_order'))
        batch_op.drop_index(batch_op.f('ix_master_dept_name'))
        batch_op.drop_index(batch_op.f('ix_master_dept_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_master_dept_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_created_time'))
        batch_op.drop_index(batch_op.f('ix_master_dept_created_id'))
        batch_op.drop_index(batch_op.f('ix_master_dept_code'))

    op.drop_table('master_dept')
    with op.batch_alter_table('source_dept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_dept_uuid'))
        batch_op.drop_index(batch_op.f('ix_source_dept_updated_id'))
        batch_op.drop_index(batch_op.f('ix_source_dept_source_type'))
        batch_op.drop_index(batch_op.f('ix_source_dept_source_org_code'))
        batch_op.drop_index(batch_op.f('ix_source_dept_source_code'))
        batch_op.drop_index(batch_op.f('ix_source_dept_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_source_dept_id'))
        batch_op.drop_index(batch_op.f('ix_source_dept_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_source_dept_created_time'))
        batch_op.drop_index(batch_op.f('ix_source_dept_created_id'))

    op.drop_table('source_dept')
    # ### end Alembic commands ###
