"""自动迁移-09241350

Revision ID: 8f4d12013554
Revises: 
Create Date: 2026-09-24 13:50:14.760619

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f4d12013554'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_kingdee_connection',
    sa.Column('name', sa.String(length=64), nullable=False, comment='连接名称'),
    sa.Column('server_url', sa.String(length=512), nullable=False, comment='服务地址(以 /k3cloud/ 结尾)'),
    sa.Column('acct_id', sa.String(length=128), nullable=False, comment='账套ID'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='授权用户'),
    sa.Column('app_id', sa.String(length=255), nullable=False, comment='应用ID'),
    sa.Column('app_secret', sa.Text(), nullable=True, comment='应用密钥(Fernet加密)'),
    sa.Column('lcid', sa.Integer(), nullable=False, comment='账套语系'),
    sa.Column('org_num', sa.Integer(), nullable=False, comment='组织编码(多组织时启用)'),
    sa.Column('connect_timeout', sa.Integer(), nullable=False, comment='连接超时(秒)'),
    sa.Column('request_timeout', sa.Integer(), nullable=False, comment='读取超时(秒)'),
    sa.Column('proxy', sa.String(length=255), nullable=True, comment='代理地址'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_erp_kingdee_connection_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_erp_kingdee_connection_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_erp_kingdee_connection_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_kingdee_connection')),
    comment='金蝶云星空连接配置表'
    )
    with op.batch_alter_table('erp_kingdee_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erp_kingdee_connection_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('erp_kingdee_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_uuid'))
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_updated_id'))
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_name'))
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_id'))
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_created_time'))
        batch_op.drop_index(batch_op.f('ix_erp_kingdee_connection_created_id'))

    op.drop_table('erp_kingdee_connection')
    # ### end Alembic commands ###
