"""自动迁移-09241713

Revision ID: 2a966bee49f3
Revises: 9f47a84ab06b
Create Date: 2026-09-24 17:13:33.304599

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a966bee49f3'
down_revision: str | None = '9f47a84ab06b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_source_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variables', sa.JSON(), nullable=True, comment='变量定义列表'))

    with op.batch_alter_table('meta_sync_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variables', sa.JSON(), nullable=True, comment='任务级变量定义'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_sync_job', schema=None) as batch_op:
        batch_op.drop_column('variables')

    with op.batch_alter_table('meta_source_object', schema=None) as batch_op:
        batch_op.drop_column('variables')

    # ### end Alembic commands ###
