"""自动迁移-10091050

Revision ID: 203324073db9
Revises: b7c1d9e4f2a0
Create Date: 2026-10-09 10:50:19.164883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203324073db9'
down_revision: Union[str, None] = 'b7c1d9e4f2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_code', sa.String(length=64), nullable=True, comment='业务员编码(来源原始，未映射也保留)'))
        batch_op.add_column(sa.Column('person_name', sa.String(length=255), nullable=True, comment='业务员姓名(来源原始)'))
        batch_op.create_index(batch_op.f('ix_metric_value_person_code'), ['person_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_value_person_code'))
        batch_op.drop_column('person_name')
        batch_op.drop_column('person_code')

    # ### end Alembic commands ###
