"""自动迁移-09241510

Revision ID: a854f011a94e
Revises: 7c66f492687a
Create Date: 2026-09-24 15:10:40.276687

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a854f011a94e'
down_revision: str | None = '7c66f492687a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_source_system',
    sa.Column('code', sa.String(length=64), nullable=False, comment='系统编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='系统名称'),
    sa.Column('connector_type', sa.String(length=32), nullable=False, comment='连接器类型(kingdee/api/database/excel/other)'),
    sa.Column('connection_id', sa.Integer(), nullable=True, comment='连接配置ID'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_source_system_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_source_system_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_source_system_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_source_system')),
    comment='来源系统元数据'
    )
    with op.batch_alter_table('meta_source_system', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_source_system_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_meta_source_system_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_system_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_system_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_system_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_system_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_system_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_system_uuid'), ['uuid'], unique=True)

    op.create_table('meta_standard_entity',
    sa.Column('code', sa.String(length=128), nullable=False, comment='标准实体编码'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='标准实体名称'),
    sa.Column('table_name', sa.String(length=128), nullable=True, comment='目标物理表'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_standard_entity_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_standard_entity_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_standard_entity_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_standard_entity')),
    comment='标准实体元数据'
    )
    with op.batch_alter_table('meta_standard_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_entity_uuid'), ['uuid'], unique=True)

    op.create_table('metric_def',
    sa.Column('code', sa.String(length=128), nullable=False, comment='指标编码'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='指标名称'),
    sa.Column('period_type', sa.String(length=16), nullable=False, comment='期间类型(day/week/month/year)'),
    sa.Column('sensitivity', sa.Integer(), nullable=False, comment='敏感级别(0普通 1敏感 2机密)'),
    sa.Column('formula', sa.Text(), nullable=True, comment='计算公式'),
    sa.Column('dimensions', sa.JSON(), nullable=True, comment='维度配置'),
    sa.Column('measures', sa.JSON(), nullable=True, comment='度量配置'),
    sa.Column('source_entity_id', sa.Integer(), nullable=True, comment='来源标准实体ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_metric_def_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_metric_def_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_metric_def_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_def')),
    comment='指标定义表'
    )
    with op.batch_alter_table('metric_def', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_def_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_metric_def_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_def_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_def_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_def_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_def_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_def_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_def_uuid'), ['uuid'], unique=True)

    op.create_table('meta_source_object',
    sa.Column('system_id', sa.Integer(), nullable=False, comment='来源系统ID'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='对象编码/表单Id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='对象名称'),
    sa.Column('query_type', sa.String(length=32), nullable=False, comment='查询类型(view/bill_query/api/database)'),
    sa.Column('request_template', sa.JSON(), nullable=True, comment='请求模板'),
    sa.Column('watermark_field', sa.String(length=128), nullable=True, comment='增量水位字段'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_source_object_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_source_object_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['meta_source_system.id'], name=op.f('fk_meta_source_object_system_id_meta_source_system'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_source_object_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_source_object')),
    sa.UniqueConstraint('system_id', 'code', name='uq_meta_source_object'),
    comment='来源对象元数据'
    )
    with op.batch_alter_table('meta_source_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_source_object_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_system_id'), ['system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_object_uuid'), ['uuid'], unique=True)

    op.create_table('meta_standard_field',
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='标准实体ID'),
    sa.Column('field_code', sa.String(length=128), nullable=False, comment='标准字段编码'),
    sa.Column('field_name', sa.String(length=255), nullable=False, comment='标准字段名称'),
    sa.Column('data_type', sa.String(length=32), nullable=False, comment='数据类型'),
    sa.Column('is_dimension', sa.Boolean(), nullable=False, comment='是否维度'),
    sa.Column('is_measure', sa.Boolean(), nullable=False, comment='是否度量'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_standard_field_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_standard_field_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['meta_standard_entity.id'], name=op.f('fk_meta_standard_field_entity_id_meta_standard_entity'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_standard_field_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_standard_field')),
    sa.UniqueConstraint('entity_id', 'field_code', name='uq_meta_standard_field'),
    comment='标准字段元数据'
    )
    with op.batch_alter_table('meta_standard_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_standard_field_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_field_code'), ['field_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_standard_field_uuid'), ['uuid'], unique=True)

    op.create_table('metric_run',
    sa.Column('metric_id', sa.Integer(), nullable=False, comment='指标定义ID'),
    sa.Column('period_type', sa.String(length=16), nullable=False, comment='期间类型'),
    sa.Column('period_value', sa.String(length=32), nullable=False, comment='期间值'),
    sa.Column('version', sa.Integer(), nullable=False, comment='指标版本'),
    sa.Column('batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('filter_signature', sa.String(length=255), nullable=True, comment='过滤条件签名'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态(pending/running/success/failed)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_metric_run_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_metric_run_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_def.id'], name=op.f('fk_metric_run_metric_id_metric_def'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_metric_run_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_run')),
    comment='指标计算批次表'
    )
    with op.batch_alter_table('metric_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_run_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_run_uuid'), ['uuid'], unique=True)

    op.create_table('meta_source_field',
    sa.Column('object_id', sa.Integer(), nullable=False, comment='来源对象ID'),
    sa.Column('field_key', sa.String(length=128), nullable=False, comment='字段Key'),
    sa.Column('field_name', sa.String(length=255), nullable=False, comment='字段名称'),
    sa.Column('data_type', sa.String(length=32), nullable=False, comment='数据类型'),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False, comment='是否主键'),
    sa.Column('is_watermark', sa.Boolean(), nullable=False, comment='是否增量水位'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_source_field_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_source_field_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['meta_source_object.id'], name=op.f('fk_meta_source_field_object_id_meta_source_object'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_source_field_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_source_field')),
    sa.UniqueConstraint('object_id', 'field_key', name='uq_meta_source_field'),
    comment='来源字段元数据'
    )
    with op.batch_alter_table('meta_source_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_source_field_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_field_key'), ['field_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_source_field_uuid'), ['uuid'], unique=True)

    op.create_table('metric_value',
    sa.Column('metric_id', sa.Integer(), nullable=False, comment='指标定义ID'),
    sa.Column('run_id', sa.Integer(), nullable=True, comment='计算批次ID'),
    sa.Column('period_type', sa.String(length=16), nullable=False, comment='期间类型'),
    sa.Column('period_value', sa.String(length=32), nullable=False, comment='期间值'),
    sa.Column('org_id', sa.Integer(), nullable=True, comment='组织ID'),
    sa.Column('dept_id', sa.Integer(), nullable=True, comment='部门ID'),
    sa.Column('person_id', sa.Integer(), nullable=True, comment='人员ID'),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False, comment='指标值'),
    sa.Column('version', sa.Integer(), nullable=False, comment='指标版本'),
    sa.Column('calc_version', sa.Integer(), nullable=False, comment='计算版本'),
    sa.Column('batch_id', sa.String(length=64), nullable=True, comment='同步批次ID'),
    sa.Column('filter_signature', sa.String(length=255), nullable=True, comment='过滤条件签名'),
    sa.Column('calc_time', sa.DateTime(timezone=True), nullable=True, comment='计算时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_metric_value_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_metric_value_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_def.id'], name=op.f('fk_metric_value_metric_id_metric_def'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['metric_run.id'], name=op.f('fk_metric_value_run_id_metric_run'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_metric_value_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_value')),
    comment='指标结果表'
    )
    with op.batch_alter_table('metric_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_value_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_dept_id'), ['dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_value_uuid'), ['uuid'], unique=True)

    op.create_table('meta_field_mapping',
    sa.Column('source_object_id', sa.Integer(), nullable=False, comment='来源对象ID'),
    sa.Column('source_field_id', sa.Integer(), nullable=False, comment='来源字段ID'),
    sa.Column('standard_field_id', sa.Integer(), nullable=False, comment='标准字段ID'),
    sa.Column('transform_type', sa.String(length=32), nullable=False, comment='加工类型'),
    sa.Column('transform_config', sa.JSON(), nullable=True, comment='加工配置'),
    sa.Column('order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_field_mapping_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_field_mapping_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_field_id'], ['meta_source_field.id'], name=op.f('fk_meta_field_mapping_source_field_id_meta_source_field'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_object_id'], ['meta_source_object.id'], name=op.f('fk_meta_field_mapping_source_object_id_meta_source_object'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_field_id'], ['meta_standard_field.id'], name=op.f('fk_meta_field_mapping_standard_field_id_meta_standard_field'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_field_mapping_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_field_mapping')),
    comment='字段映射元数据'
    )
    with op.batch_alter_table('meta_field_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_source_field_id'), ['source_field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_source_object_id'), ['source_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_standard_field_id'), ['standard_field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_field_mapping_uuid'), ['uuid'], unique=True)

    op.create_table('metric_trace',
    sa.Column('metric_run_id', sa.Integer(), nullable=True, comment='计算批次ID'),
    sa.Column('metric_value_id', sa.Integer(), nullable=True, comment='指标结果ID'),
    sa.Column('dwd_row_id', sa.String(length=128), nullable=True, comment='标准明细行ID'),
    sa.Column('source_batch_id', sa.String(length=64), nullable=True, comment='来源批次ID'),
    sa.Column('source_object_id', sa.Integer(), nullable=True, comment='来源对象ID'),
    sa.Column('source_pk', sa.String(length=128), nullable=True, comment='来源主键'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_metric_trace_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_metric_trace_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_run_id'], ['metric_run.id'], name=op.f('fk_metric_trace_metric_run_id_metric_run'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metric_value_id'], ['metric_value.id'], name=op.f('fk_metric_trace_metric_value_id_metric_value'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_metric_trace_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_trace')),
    comment='指标追溯表'
    )
    with op.batch_alter_table('metric_trace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_trace_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_dwd_row_id'), ['dwd_row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_metric_run_id'), ['metric_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_metric_value_id'), ['metric_value_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_trace_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_trace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_trace_uuid'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_updated_id'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_metric_value_id'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_metric_run_id'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_id'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_dwd_row_id'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_created_time'))
        batch_op.drop_index(batch_op.f('ix_metric_trace_created_id'))

    op.drop_table('metric_trace')
    with op.batch_alter_table('meta_field_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_standard_field_id'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_source_object_id'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_source_field_id'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_field_mapping_created_id'))

    op.drop_table('meta_field_mapping')
    with op.batch_alter_table('metric_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_value_uuid'))
        batch_op.drop_index(batch_op.f('ix_metric_value_updated_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_run_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_person_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_org_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_metric_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_metric_value_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_dept_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_metric_value_created_time'))
        batch_op.drop_index(batch_op.f('ix_metric_value_created_id'))

    op.drop_table('metric_value')
    with op.batch_alter_table('meta_source_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_source_field_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_object_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_field_key'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_source_field_created_id'))

    op.drop_table('meta_source_field')
    with op.batch_alter_table('metric_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_run_uuid'))
        batch_op.drop_index(batch_op.f('ix_metric_run_updated_id'))
        batch_op.drop_index(batch_op.f('ix_metric_run_metric_id'))
        batch_op.drop_index(batch_op.f('ix_metric_run_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_metric_run_id'))
        batch_op.drop_index(batch_op.f('ix_metric_run_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_metric_run_created_time'))
        batch_op.drop_index(batch_op.f('ix_metric_run_created_id'))
        batch_op.drop_index(batch_op.f('ix_metric_run_batch_id'))

    op.drop_table('metric_run')
    with op.batch_alter_table('meta_standard_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_field_code'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_entity_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_field_created_id'))

    op.drop_table('meta_standard_field')
    with op.batch_alter_table('meta_source_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_source_object_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_system_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_created_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_object_code'))

    op.drop_table('meta_source_object')
    with op.batch_alter_table('metric_def', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_def_uuid'))
        batch_op.drop_index(batch_op.f('ix_metric_def_updated_id'))
        batch_op.drop_index(batch_op.f('ix_metric_def_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_metric_def_id'))
        batch_op.drop_index(batch_op.f('ix_metric_def_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_metric_def_created_time'))
        batch_op.drop_index(batch_op.f('ix_metric_def_created_id'))
        batch_op.drop_index(batch_op.f('ix_metric_def_code'))

    op.drop_table('metric_def')
    with op.batch_alter_table('meta_standard_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_created_id'))
        batch_op.drop_index(batch_op.f('ix_meta_standard_entity_code'))

    op.drop_table('meta_standard_entity')
    with op.batch_alter_table('meta_source_system', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_source_system_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_source_system_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_system_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_source_system_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_system_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_system_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_source_system_created_id'))
        batch_op.drop_index(batch_op.f('ix_meta_source_system_code'))

    op.drop_table('meta_source_system')
    # ### end Alembic commands ###
