"""自动迁移-09271024

Revision ID: 6f7f526b35cb
Revises: 7f1be4dbfb40
Create Date: 2026-09-27 10:24:38.631378

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f7f526b35cb'
down_revision: str | None = '7f1be4dbfb40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept_business_mapping',
    sa.Column('sys_dept_id', sa.Integer(), nullable=False, comment='系统权限部门ID'),
    sa.Column('master_dept_id', sa.Integer(), nullable=False, comment='业务标准部门ID'),
    sa.Column('match_mode', sa.String(length=16), nullable=False, comment='绑定方式'),
    sa.Column('confidence', sa.Integer(), nullable=False, comment='置信度'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:失效)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_sys_dept_business_mapping_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_sys_dept_business_mapping_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['master_dept_id'], ['master_dept.id'], name=op.f('fk_sys_dept_business_mapping_master_dept_id_master_dept'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sys_dept_id'], ['sys_dept.id'], name=op.f('fk_sys_dept_business_mapping_sys_dept_id_sys_dept'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_sys_dept_business_mapping_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_dept_business_mapping')),
    sa.UniqueConstraint('sys_dept_id', 'master_dept_id', name='uq_sys_dept_business_mapping'),
    comment='权限部门与业务标准部门绑定表'
    )
    with op.batch_alter_table('sys_dept_business_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_master_dept_id'), ['master_dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_sys_dept_id'), ['sys_dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sys_dept_business_mapping_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_dept_business_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_uuid'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_updated_id'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_sys_dept_id'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_master_dept_id'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_created_time'))
        batch_op.drop_index(batch_op.f('ix_sys_dept_business_mapping_created_id'))

    op.drop_table('sys_dept_business_mapping')
    # ### end Alembic commands ###
