"""自动迁移-09281113

Revision ID: 6dba8143ca7a
Revises: 522401c54b80
Create Date: 2026-09-28 11:13:48.714974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dba8143ca7a'
down_revision: Union[str, None] = '522401c54b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_connection',
    sa.Column('name', sa.String(length=64), nullable=False, comment='连接名称'),
    sa.Column('base_url', sa.String(length=255), nullable=False, comment='接口域名'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='读取超时(秒)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_crm_connection_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_crm_connection_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_crm_connection_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_connection')),
    comment='CRM 连接配置表'
    )
    with op.batch_alter_table('crm_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_connection_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_connection_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_connection_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_connection_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_connection_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_connection_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_crm_connection_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_connection_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_connection_uuid'))
        batch_op.drop_index(batch_op.f('ix_crm_connection_updated_id'))
        batch_op.drop_index(batch_op.f('ix_crm_connection_name'))
        batch_op.drop_index(batch_op.f('ix_crm_connection_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_crm_connection_id'))
        batch_op.drop_index(batch_op.f('ix_crm_connection_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_crm_connection_created_time'))
        batch_op.drop_index(batch_op.f('ix_crm_connection_created_id'))

    op.drop_table('crm_connection')
    # ### end Alembic commands ###
