"""自动迁移-09241549

Revision ID: 9f47a84ab06b
Revises: a854f011a94e
Create Date: 2026-09-24 15:49:23.443545

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f47a84ab06b'
down_revision: str | None = 'a854f011a94e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_sync_job',
    sa.Column('name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('source_system_id', sa.Integer(), nullable=False, comment='来源系统ID'),
    sa.Column('source_object_id', sa.Integer(), nullable=False, comment='来源对象ID'),
    sa.Column('standard_entity_id', sa.Integer(), nullable=True, comment='标准实体ID'),
    sa.Column('org_code', sa.String(length=64), nullable=True, comment='组织编码'),
    sa.Column('cron_expr', sa.String(length=64), nullable=False, comment='Cron表达式'),
    sa.Column('request_params', sa.JSON(), nullable=True, comment='请求参数/Model'),
    sa.Column('sync_mode', sa.String(length=16), nullable=False, comment='同步模式(full/incremental)'),
    sa.Column('watermark_field', sa.String(length=128), nullable=True, comment='增量水位字段'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_sync_job_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_sync_job_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_object_id'], ['meta_source_object.id'], name=op.f('fk_meta_sync_job_source_object_id_meta_source_object'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_system_id'], ['meta_source_system.id'], name=op.f('fk_meta_sync_job_source_system_id_meta_source_system'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_entity_id'], ['meta_standard_entity.id'], name=op.f('fk_meta_sync_job_standard_entity_id_meta_standard_entity'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_sync_job_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_sync_job')),
    comment='元数据同步任务表'
    )
    with op.batch_alter_table('meta_sync_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_sync_job_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_org_code'), ['org_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_source_object_id'), ['source_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_source_system_id'), ['source_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_job_uuid'), ['uuid'], unique=True)

    op.create_table('meta_sync_run',
    sa.Column('job_id', sa.Integer(), nullable=False, comment='同步任务ID'),
    sa.Column('batch_id', sa.String(length=64), nullable=True, comment='批次ID'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态(pending/running/success/failed)'),
    sa.Column('row_count', sa.Integer(), nullable=False, comment='行数'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('rows_json', sa.JSON(), nullable=True, comment='原始返回数据'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_meta_sync_run_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_meta_sync_run_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['meta_sync_job.id'], name=op.f('fk_meta_sync_run_job_id_meta_sync_job'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_meta_sync_run_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_sync_run')),
    comment='元数据同步运行日志'
    )
    with op.batch_alter_table('meta_sync_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_sync_run_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meta_sync_run_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_sync_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_job_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_created_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_batch_id'))

    op.drop_table('meta_sync_run')
    with op.batch_alter_table('meta_sync_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_uuid'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_updated_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_source_system_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_source_object_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_org_code'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_created_time'))
        batch_op.drop_index(batch_op.f('ix_meta_sync_job_created_id'))

    op.drop_table('meta_sync_job')
    # ### end Alembic commands ###
