"""自动迁移-09271158

Revision ID: d63967f5af7c
Revises: 1a0713e70781
Create Date: 2026-09-27 11:58:07.519020

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd63967f5af7c'
down_revision: str | None = '1a0713e70781'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_code', sa.String(length=64), nullable=True, comment='核算维度部门编码(原始，未映射也保留)'))
        batch_op.add_column(sa.Column('dept_name', sa.String(length=255), nullable=True, comment='核算维度部门名称(原始)'))
        batch_op.create_index(batch_op.f('ix_metric_value_dept_code'), ['dept_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metric_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_value_dept_code'))
        batch_op.drop_column('dept_name')
        batch_op.drop_column('dept_code')

    # ### end Alembic commands ###
