"""自动迁移-09241401

Revision ID: 86a5da24a026
Revises: 8f4d12013554
Create Date: 2026-09-24 14:01:08.879624

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86a5da24a026'
down_revision: str | None = '8f4d12013554'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_org',
    sa.Column('code', sa.String(length=64), nullable=False, comment='组织编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='组织名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级组织ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='显示排序'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_master_org_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_master_org_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['master_org.id'], name=op.f('fk_master_org_parent_id_master_org'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_master_org_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_org')),
    comment='内部标准组织表'
    )
    with op.batch_alter_table('master_org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_org_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_master_org_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_uuid'), ['uuid'], unique=True)

    op.create_table('source_org',
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='来源类型(kingdee/crm/excel/other)'),
    sa.Column('source_code', sa.String(length=128), nullable=False, comment='来源组织编码'),
    sa.Column('source_name', sa.String(length=255), nullable=False, comment='来源组织名称'),
    sa.Column('source_parent_code', sa.String(length=128), nullable=True, comment='来源上级编码'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始数据'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:停用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_source_org_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_source_org_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_source_org_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_org')),
    sa.UniqueConstraint('source_type', 'source_code', name='uq_source_org_type_code'),
    comment='外部来源组织表'
    )
    with op.batch_alter_table('source_org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_org_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_source_code'), ['source_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_org_uuid'), ['uuid'], unique=True)

    op.create_table('source_person',
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='来源类型'),
    sa.Column('source_code', sa.String(length=128), nullable=False, comment='来源人员编码'),
    sa.Column('source_name', sa.String(length=255), nullable=False, comment='来源人员姓名'),
    sa.Column('source_org_code', sa.String(length=128), nullable=True, comment='来源组织编码'),
    sa.Column('mobile', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始数据'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:停用)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_source_person_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_source_person_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_source_person_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_person')),
    sa.UniqueConstraint('source_type', 'source_code', name='uq_source_person_type_code'),
    comment='外部来源人员表'
    )
    with op.batch_alter_table('source_person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_person_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_mobile'), ['mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_source_code'), ['source_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_person_uuid'), ['uuid'], unique=True)

    op.create_table('master_org_mapping',
    sa.Column('source_org_id', sa.Integer(), nullable=False, comment='来源组织ID'),
    sa.Column('master_org_id', sa.Integer(), nullable=False, comment='内部标准组织ID'),
    sa.Column('match_mode', sa.String(length=16), nullable=False, comment='匹配方式(exact/fuzzy/manual)'),
    sa.Column('confidence', sa.Integer(), nullable=False, comment='匹配置信度(0-100)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:失效)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_master_org_mapping_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_master_org_mapping_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['master_org_id'], ['master_org.id'], name=op.f('fk_master_org_mapping_master_org_id_master_org'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_org_id'], ['source_org.id'], name=op.f('fk_master_org_mapping_source_org_id_source_org'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_master_org_mapping_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_org_mapping')),
    comment='来源组织映射表'
    )
    with op.batch_alter_table('master_org_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_org_mapping_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_master_org_id'), ['master_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_source_org_id'), ['source_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_org_mapping_uuid'), ['uuid'], unique=True)

    op.create_table('master_person',
    sa.Column('code', sa.String(length=64), nullable=False, comment='人员编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='人员姓名'),
    sa.Column('org_id', sa.Integer(), nullable=True, comment='所属组织ID'),
    sa.Column('mobile', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_master_person_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_master_person_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['master_org.id'], name=op.f('fk_master_person_org_id_master_org'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_master_person_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_person')),
    comment='内部标准人员表'
    )
    with op.batch_alter_table('master_person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_person_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_master_person_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mobile'), ['mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_uuid'), ['uuid'], unique=True)

    op.create_table('master_person_mapping',
    sa.Column('source_person_id', sa.Integer(), nullable=False, comment='来源人员ID'),
    sa.Column('master_person_id', sa.Integer(), nullable=False, comment='内部标准人员ID'),
    sa.Column('match_mode', sa.String(length=16), nullable=False, comment='匹配方式(exact/fuzzy/manual)'),
    sa.Column('confidence', sa.Integer(), nullable=False, comment='匹配置信度(0-100)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:有效 1:失效)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_master_person_mapping_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_master_person_mapping_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['master_person_id'], ['master_person.id'], name=op.f('fk_master_person_mapping_master_person_id_master_person'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_person_id'], ['source_person.id'], name=op.f('fk_master_person_mapping_source_person_id_source_person'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_master_person_mapping_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_person_mapping')),
    comment='来源人员映射表'
    )
    with op.batch_alter_table('master_person_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_person_mapping_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_master_person_id'), ['master_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_source_person_id'), ['source_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_person_mapping_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_person_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_uuid'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_updated_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_source_person_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_master_person_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_created_time'))
        batch_op.drop_index(batch_op.f('ix_master_person_mapping_created_id'))

    op.drop_table('master_person_mapping')
    with op.batch_alter_table('master_person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_person_uuid'))
        batch_op.drop_index(batch_op.f('ix_master_person_updated_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_org_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_name'))
        batch_op.drop_index(batch_op.f('ix_master_person_mobile'))
        batch_op.drop_index(batch_op.f('ix_master_person_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_master_person_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_email'))
        batch_op.drop_index(batch_op.f('ix_master_person_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_created_time'))
        batch_op.drop_index(batch_op.f('ix_master_person_created_id'))
        batch_op.drop_index(batch_op.f('ix_master_person_code'))

    op.drop_table('master_person')
    with op.batch_alter_table('master_org_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_uuid'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_updated_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_source_org_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_master_org_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_created_time'))
        batch_op.drop_index(batch_op.f('ix_master_org_mapping_created_id'))

    op.drop_table('master_org_mapping')
    with op.batch_alter_table('source_person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_person_uuid'))
        batch_op.drop_index(batch_op.f('ix_source_person_updated_id'))
        batch_op.drop_index(batch_op.f('ix_source_person_source_type'))
        batch_op.drop_index(batch_op.f('ix_source_person_source_code'))
        batch_op.drop_index(batch_op.f('ix_source_person_mobile'))
        batch_op.drop_index(batch_op.f('ix_source_person_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_source_person_id'))
        batch_op.drop_index(batch_op.f('ix_source_person_email'))
        batch_op.drop_index(batch_op.f('ix_source_person_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_source_person_created_time'))
        batch_op.drop_index(batch_op.f('ix_source_person_created_id'))

    op.drop_table('source_person')
    with op.batch_alter_table('source_org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_org_uuid'))
        batch_op.drop_index(batch_op.f('ix_source_org_updated_id'))
        batch_op.drop_index(batch_op.f('ix_source_org_source_type'))
        batch_op.drop_index(batch_op.f('ix_source_org_source_code'))
        batch_op.drop_index(batch_op.f('ix_source_org_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_source_org_id'))
        batch_op.drop_index(batch_op.f('ix_source_org_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_source_org_created_time'))
        batch_op.drop_index(batch_op.f('ix_source_org_created_id'))

    op.drop_table('source_org')
    with op.batch_alter_table('master_org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_org_uuid'))
        batch_op.drop_index(batch_op.f('ix_master_org_updated_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_parent_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_order'))
        batch_op.drop_index(batch_op.f('ix_master_org_name'))
        batch_op.drop_index(batch_op.f('ix_master_org_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_master_org_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_created_time'))
        batch_op.drop_index(batch_op.f('ix_master_org_created_id'))
        batch_op.drop_index(batch_op.f('ix_master_org_code'))

    op.drop_table('master_org')
    # ### end Alembic commands ###
