"""自动迁移-09271101

Revision ID: 1a0713e70781
Revises: 6f7f526b35cb
Create Date: 2026-09-27 11:01:37.339627

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a0713e70781'
down_revision: str | None = '6f7f526b35cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_sync_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_value', sa.String(length=32), nullable=True, comment='取数期间(如 2026-09；按期间回补时使用)'))
        batch_op.create_index(batch_op.f('ix_meta_sync_run_period_value'), ['period_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_sync_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_sync_run_period_value'))
        batch_op.drop_column('period_value')

    # ### end Alembic commands ###
