"""自动迁移-09271007

Revision ID: 7f1be4dbfb40
Revises: 2a966bee49f3
Create Date: 2026-09-27 10:07:14.385370

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f1be4dbfb40'
down_revision: str | None = '2a966bee49f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_person_org', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否主任岗'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_person_org', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
