"""自动迁移-09281022

Revision ID: 522401c54b80
Revises: a808cb09902b
Create Date: 2026-09-28 10:22:12.903527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522401c54b80'
down_revision: Union[str, None] = 'a808cb09902b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_api_log',
    sa.Column('client_id', sa.Integer(), nullable=True, comment='应用ID'),
    sa.Column('app_id', sa.String(length=64), nullable=True, comment='应用标识'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='请求路径'),
    sa.Column('method', sa.String(length=16), nullable=False, comment='请求方法'),
    sa.Column('params', sa.JSON(), nullable=True, comment='请求参数(已脱敏)'),
    sa.Column('response_code', sa.Integer(), nullable=False, comment='业务状态码'),
    sa.Column('http_status', sa.Integer(), nullable=False, comment='HTTP 状态码'),
    sa.Column('cost_ms', sa.Integer(), nullable=False, comment='耗时(毫秒)'),
    sa.Column('client_ip', sa.String(length=64), nullable=True, comment='调用方 IP'),
    sa.Column('description', sa.Text(), nullable=True, comment='接口说明'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_open_api_log_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_open_api_log_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_open_api_log_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_api_log')),
    comment='开放接口调用日志表'
    )
    with op.batch_alter_table('open_api_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_api_log_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_api_log_uuid'), ['uuid'], unique=True)

    op.create_table('open_client',
    sa.Column('app_id', sa.String(length=64), nullable=False, comment='应用标识'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='应用名称'),
    sa.Column('secret_hash', sa.String(length=255), nullable=False, comment='密钥哈希(PBKDF2，不可逆)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0:启用 1:停用)'),
    sa.Column('ip_whitelist', sa.String(length=500), nullable=True, comment='调用方 IP 白名单，逗号分隔，空=不限制'),
    sa.Column('token_ttl_seconds', sa.Integer(), nullable=False, comment='令牌有效期(秒)'),
    sa.Column('rate_limit', sa.Integer(), nullable=False, comment='每分钟最大请求数'),
    sa.Column('allow_dept_detail', sa.Boolean(), nullable=False, comment='是否允许查询核算维度明细(默认仅组织合计)'),
    sa.Column('allow_run_calc', sa.Boolean(), nullable=False, comment='是否允许触发指标重算'),
    sa.Column('org_scope', sa.JSON(), nullable=True, comment='允许的组织编码列表，空=全部启用组织'),
    sa.Column('expire_time', sa.DateTime(timezone=True), nullable=True, comment='凭证到期时间，空=长期有效'),
    sa.Column('contact', sa.String(length=128), nullable=True, comment='联系人'),
    sa.Column('description', sa.Text(), nullable=True, comment='用途备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('deleted_time', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], name=op.f('fk_open_client_created_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], name=op.f('fk_open_client_deleted_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], name=op.f('fk_open_client_updated_id_sys_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_client')),
    comment='开放接口接入应用表'
    )
    with op.batch_alter_table('open_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_client_app_id'), ['app_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_open_client_created_id'), ['created_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_client_created_time'), ['created_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_client_deleted_id'), ['deleted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_client_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_client_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_client_updated_id'), ['updated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_client_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_client_uuid'))
        batch_op.drop_index(batch_op.f('ix_open_client_updated_id'))
        batch_op.drop_index(batch_op.f('ix_open_client_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_open_client_id'))
        batch_op.drop_index(batch_op.f('ix_open_client_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_open_client_created_time'))
        batch_op.drop_index(batch_op.f('ix_open_client_created_id'))
        batch_op.drop_index(batch_op.f('ix_open_client_app_id'))

    op.drop_table('open_client')
    with op.batch_alter_table('open_api_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_api_log_uuid'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_updated_id'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_id'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_deleted_id'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_created_time'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_created_id'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_client_id'))
        batch_op.drop_index(batch_op.f('ix_open_api_log_app_id'))

    op.drop_table('open_api_log')
    # ### end Alembic commands ###
