"""自动迁移-10091055

Revision ID: cd6a5655eba2
Revises: d81f6c2a7e35
Create Date: 2026-10-09 10:55:17.436291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd6a5655eba2'
down_revision: Union[str, None] = 'd81f6c2a7e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_client', schema=None) as batch_op:
        batch_op.alter_column('allow_person_detail',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_comment='是否允许查询业务员明细(默认不开放)',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_client', schema=None) as batch_op:
        batch_op.alter_column('allow_person_detail',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否允许查询业务员明细(默认不开放)',
               existing_nullable=False)

    # ### end Alembic commands ###
